CREATE DATABASE HI;
USE HI;
CREATE TABLE GAP11(
  Id INT NOT NULL ,
  NAME VARCHAR(50) NOT NULL,
  AGE INT NULL
  
);
INSERT INTO GAP11(Id,NAME)
VALUES
(1,'GNANESWAR'),
(2,'SUBHASH');
UPDATE GAP11
SET AGE=21 
WHERE AGE IS NULL;
ALTER TABLE GAP11
ALTER COLUMN AGE INT NOT NULL;
SELECT*FROM GAP11;


