CREATE DATABASE ER;
USE ER;
CREATE TABLE GAPP(
    ID INT,
    NAME VARCHAR(50),
    MANAGER_ID INT
); 
INSERT INTO GAPP(ID,NAME,MANAGER_ID)
VALUES
(1,'GNANESWAR',NULL),
(2,'ANJNAIPRASAD',2),
(3,'KOKKKIRALA',5);
SELECT 
  E.NAME AS EMPLOYEE,
  M.NAME AS MANAGER
FROM GAPP E
LEFT JOIN GAPP M
ON E.MANAGER_ID = M.ID;

